export const hours = [
    {
        "time_epoch": 1736208000,
        "time": "2025-01-07 00:00",
        "temp_c": 2.5,
        "temp_f": 36.5,
        "is_day": 0,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 1.6,
        "wind_kph": 2.5,
        "wind_degree": 245,
        "wind_dir": "WSW",
        "pressure_mb": 999,
        "pressure_in": 29.49,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 91,
        "cloud": 37,
        "feelslike_c": 2.5,
        "feelslike_f": 36.4,
        "windchill_c": 2.5,
        "windchill_f": 36.4,
        "heatindex_c": 2.5,
        "heatindex_f": 36.4,
        "dewpoint_c": 1.1,
        "dewpoint_f": 34,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 2.4,
        "gust_kph": 3.9,
        "uv": 0
    },
    {
        "time_epoch": 1736211600,
        "time": "2025-01-07 01:00",
        "temp_c": 2.3,
        "temp_f": 36.1,
        "is_day": 0,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 1.1,
        "wind_kph": 1.8,
        "wind_degree": 332,
        "wind_dir": "NNW",
        "pressure_mb": 999,
        "pressure_in": 29.49,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 92,
        "cloud": 33,
        "feelslike_c": 2.3,
        "feelslike_f": 36.1,
        "windchill_c": 2.3,
        "windchill_f": 36.1,
        "heatindex_c": 2.3,
        "heatindex_f": 36.1,
        "dewpoint_c": 1,
        "dewpoint_f": 33.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 1.8,
        "gust_kph": 2.8,
        "uv": 0
    },
    {
        "time_epoch": 1736215200,
        "time": "2025-01-07 02:00",
        "temp_c": 2,
        "temp_f": 35.6,
        "is_day": 0,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 2.7,
        "wind_kph": 4.3,
        "wind_degree": 17,
        "wind_dir": "NNE",
        "pressure_mb": 999,
        "pressure_in": 29.5,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 92,
        "cloud": 28,
        "feelslike_c": 1,
        "feelslike_f": 33.8,
        "windchill_c": 1,
        "windchill_f": 33.8,
        "heatindex_c": 2,
        "heatindex_f": 35.6,
        "dewpoint_c": 0.9,
        "dewpoint_f": 33.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 4.3,
        "gust_kph": 6.9,
        "uv": 0
    },
    {
        "time_epoch": 1736218800,
        "time": "2025-01-07 03:00",
        "temp_c": 1.8,
        "temp_f": 35.3,
        "is_day": 0,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 1.1,
        "wind_kph": 1.8,
        "wind_degree": 42,
        "wind_dir": "NE",
        "pressure_mb": 1000,
        "pressure_in": 29.52,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 92,
        "cloud": 34,
        "feelslike_c": 1.8,
        "feelslike_f": 35.3,
        "windchill_c": 1.8,
        "windchill_f": 35.3,
        "heatindex_c": 1.8,
        "heatindex_f": 35.3,
        "dewpoint_c": 0.7,
        "dewpoint_f": 33.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 1.8,
        "gust_kph": 2.9,
        "uv": 0
    },
    {
        "time_epoch": 1736222400,
        "time": "2025-01-07 04:00",
        "temp_c": 1.6,
        "temp_f": 34.9,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 2.9,
        "wind_kph": 4.7,
        "wind_degree": 359,
        "wind_dir": "N",
        "pressure_mb": 1000,
        "pressure_in": 29.52,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 92,
        "cloud": 24,
        "feelslike_c": 0.4,
        "feelslike_f": 32.7,
        "windchill_c": 0.4,
        "windchill_f": 32.7,
        "heatindex_c": 1.6,
        "heatindex_f": 34.9,
        "dewpoint_c": 0.4,
        "dewpoint_f": 32.8,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 4.7,
        "gust_kph": 7.6,
        "uv": 0
    },
    {
        "time_epoch": 1736226000,
        "time": "2025-01-07 05:00",
        "temp_c": 1.4,
        "temp_f": 34.5,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 2.7,
        "wind_kph": 4.3,
        "wind_degree": 10,
        "wind_dir": "N",
        "pressure_mb": 1000,
        "pressure_in": 29.54,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 91,
        "cloud": 20,
        "feelslike_c": 0.3,
        "feelslike_f": 32.6,
        "windchill_c": 0.3,
        "windchill_f": 32.6,
        "heatindex_c": 1.4,
        "heatindex_f": 34.5,
        "dewpoint_c": 0.1,
        "dewpoint_f": 32.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 4.4,
        "gust_kph": 7.1,
        "uv": 0
    },
    {
        "time_epoch": 1736229600,
        "time": "2025-01-07 06:00",
        "temp_c": 1.2,
        "temp_f": 34.1,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 3.1,
        "wind_kph": 5,
        "wind_degree": 344,
        "wind_dir": "NNW",
        "pressure_mb": 1000,
        "pressure_in": 29.54,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 90,
        "cloud": 13,
        "feelslike_c": -0.3,
        "feelslike_f": 31.5,
        "windchill_c": -0.3,
        "windchill_f": 31.5,
        "heatindex_c": 1.2,
        "heatindex_f": 34.1,
        "dewpoint_c": -0.3,
        "dewpoint_f": 31.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 5.2,
        "gust_kph": 8.3,
        "uv": 0
    },
    {
        "time_epoch": 1736233200,
        "time": "2025-01-07 07:00",
        "temp_c": 1,
        "temp_f": 33.8,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 3.1,
        "wind_kph": 5,
        "wind_degree": 327,
        "wind_dir": "NNW",
        "pressure_mb": 1001,
        "pressure_in": 29.55,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 88,
        "cloud": 23,
        "feelslike_c": -0.5,
        "feelslike_f": 31.2,
        "windchill_c": -0.5,
        "windchill_f": 31.2,
        "heatindex_c": 1,
        "heatindex_f": 33.8,
        "dewpoint_c": -0.7,
        "dewpoint_f": 30.8,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 5.2,
        "gust_kph": 8.4,
        "uv": 0
    },
    {
        "time_epoch": 1736236800,
        "time": "2025-01-07 08:00",
        "temp_c": 1.2,
        "temp_f": 34.2,
        "is_day": 1,
        "condition": {
            "text": "Light sleet",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/317.png",
            "code": 1204
        },
        "wind_mph": 2.2,
        "wind_kph": 3.6,
        "wind_degree": 316,
        "wind_dir": "NW",
        "pressure_mb": 997,
        "pressure_in": 29.44,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 93,
        "cloud": 100,
        "feelslike_c": 0.1,
        "feelslike_f": 32.2,
        "windchill_c": 0.1,
        "windchill_f": 32.2,
        "heatindex_c": 0.9,
        "heatindex_f": 33.6,
        "dewpoint_c": -0.9,
        "dewpoint_f": 30.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 5,
        "vis_miles": 3,
        "gust_mph": 3.8,
        "gust_kph": 6,
        "uv": 1
    },
    {
        "time_epoch": 1736240400,
        "time": "2025-01-07 09:00",
        "temp_c": 1.2,
        "temp_f": 34.1,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 1.8,
        "wind_kph": 2.9,
        "wind_degree": 317,
        "wind_dir": "NW",
        "pressure_mb": 1002,
        "pressure_in": 29.58,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 86,
        "cloud": 22,
        "feelslike_c": 1.2,
        "feelslike_f": 34.1,
        "windchill_c": 1.2,
        "windchill_f": 34.1,
        "heatindex_c": 1.2,
        "heatindex_f": 34.1,
        "dewpoint_c": -0.9,
        "dewpoint_f": 30.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 2.8,
        "gust_kph": 4.6,
        "uv": 2
    },
    {
        "time_epoch": 1736244000,
        "time": "2025-01-07 10:00",
        "temp_c": 2,
        "temp_f": 35.6,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 1.3,
        "wind_kph": 2.2,
        "wind_degree": 310,
        "wind_dir": "NW",
        "pressure_mb": 1002,
        "pressure_in": 29.58,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 81,
        "cloud": 20,
        "feelslike_c": 2,
        "feelslike_f": 35.5,
        "windchill_c": 2,
        "windchill_f": 35.5,
        "heatindex_c": 2,
        "heatindex_f": 35.5,
        "dewpoint_c": -0.9,
        "dewpoint_f": 30.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 1.9,
        "gust_kph": 3.1,
        "uv": 2
    },
    {
        "time_epoch": 1736247600,
        "time": "2025-01-07 11:00",
        "temp_c": 2.7,
        "temp_f": 36.8,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 1.8,
        "wind_kph": 2.9,
        "wind_degree": 259,
        "wind_dir": "W",
        "pressure_mb": 1002,
        "pressure_in": 29.59,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 77,
        "cloud": 10,
        "feelslike_c": 2.7,
        "feelslike_f": 36.8,
        "windchill_c": 2.7,
        "windchill_f": 36.8,
        "heatindex_c": 2.7,
        "heatindex_f": 36.8,
        "dewpoint_c": -0.9,
        "dewpoint_f": 30.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 2.4,
        "gust_kph": 3.8,
        "uv": 2
    },
    {
        "time_epoch": 1736251200,
        "time": "2025-01-07 12:00",
        "temp_c": 3.3,
        "temp_f": 37.9,
        "is_day": 1,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 2.5,
        "wind_kph": 4,
        "wind_degree": 241,
        "wind_dir": "WSW",
        "pressure_mb": 1002,
        "pressure_in": 29.59,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 74,
        "cloud": 46,
        "feelslike_c": 2.6,
        "feelslike_f": 36.7,
        "windchill_c": 2.6,
        "windchill_f": 36.7,
        "heatindex_c": 3.3,
        "heatindex_f": 37.9,
        "dewpoint_c": -0.9,
        "dewpoint_f": 30.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 3.2,
        "gust_kph": 5.1,
        "uv": 2
    },
    {
        "time_epoch": 1736254800,
        "time": "2025-01-07 13:00",
        "temp_c": 3.5,
        "temp_f": 38.4,
        "is_day": 1,
        "condition": {
            "text": "Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
            "code": 1006
        },
        "wind_mph": 3.1,
        "wind_kph": 5,
        "wind_degree": 242,
        "wind_dir": "WSW",
        "pressure_mb": 1002,
        "pressure_in": 29.59,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 73,
        "cloud": 86,
        "feelslike_c": 2.4,
        "feelslike_f": 36.4,
        "windchill_c": 2.4,
        "windchill_f": 36.4,
        "heatindex_c": 3.6,
        "heatindex_f": 38.4,
        "dewpoint_c": -0.9,
        "dewpoint_f": 30.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 4.1,
        "gust_kph": 6.7,
        "uv": 1
    },
    {
        "time_epoch": 1736258400,
        "time": "2025-01-07 14:00",
        "temp_c": 3.7,
        "temp_f": 38.7,
        "is_day": 1,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 2.9,
        "wind_kph": 4.7,
        "wind_degree": 243,
        "wind_dir": "WSW",
        "pressure_mb": 1002,
        "pressure_in": 29.59,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 72,
        "cloud": 27,
        "feelslike_c": 2.8,
        "feelslike_f": 37,
        "windchill_c": 2.8,
        "windchill_f": 37,
        "heatindex_c": 3.7,
        "heatindex_f": 38.7,
        "dewpoint_c": -0.8,
        "dewpoint_f": 30.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 3.9,
        "gust_kph": 6.3,
        "uv": 2
    },
    {
        "time_epoch": 1736262000,
        "time": "2025-01-07 15:00",
        "temp_c": 3.6,
        "temp_f": 38.4,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 2.2,
        "wind_kph": 3.6,
        "wind_degree": 257,
        "wind_dir": "WSW",
        "pressure_mb": 1002,
        "pressure_in": 29.6,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 74,
        "cloud": 11,
        "feelslike_c": 3.1,
        "feelslike_f": 37.6,
        "windchill_c": 3.1,
        "windchill_f": 37.6,
        "heatindex_c": 3.6,
        "heatindex_f": 38.4,
        "dewpoint_c": -0.6,
        "dewpoint_f": 30.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 3.2,
        "gust_kph": 5.1,
        "uv": 2
    },
    {
        "time_epoch": 1736265600,
        "time": "2025-01-07 16:00",
        "temp_c": 2.7,
        "temp_f": 36.9,
        "is_day": 1,
        "condition": {
            "text": "Overcast ",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
            "code": 1009
        },
        "wind_mph": 1.6,
        "wind_kph": 2.5,
        "wind_degree": 267,
        "wind_dir": "W",
        "pressure_mb": 1003,
        "pressure_in": 29.62,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 79,
        "cloud": 100,
        "feelslike_c": 2.7,
        "feelslike_f": 36.9,
        "windchill_c": 2.7,
        "windchill_f": 36.9,
        "heatindex_c": 2.7,
        "heatindex_f": 36.9,
        "dewpoint_c": -0.5,
        "dewpoint_f": 31,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 2.5,
        "gust_kph": 4.1,
        "uv": 1
    },
    {
        "time_epoch": 1736269200,
        "time": "2025-01-07 17:00",
        "temp_c": 2.5,
        "temp_f": 36.5,
        "is_day": 0,
        "condition": {
            "text": "Overcast ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
            "code": 1009
        },
        "wind_mph": 0.2,
        "wind_kph": 0.4,
        "wind_degree": 336,
        "wind_dir": "NNW",
        "pressure_mb": 1003,
        "pressure_in": 29.62,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 80,
        "cloud": 100,
        "feelslike_c": 2.5,
        "feelslike_f": 36.5,
        "windchill_c": 2.5,
        "windchill_f": 36.5,
        "heatindex_c": 2.5,
        "heatindex_f": 36.5,
        "dewpoint_c": -0.5,
        "dewpoint_f": 31.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 0.4,
        "gust_kph": 0.6,
        "uv": 0
    },
    {
        "time_epoch": 1736272800,
        "time": "2025-01-07 18:00",
        "temp_c": 2.5,
        "temp_f": 36.5,
        "is_day": 0,
        "condition": {
            "text": "Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
            "code": 1006
        },
        "wind_mph": 0.7,
        "wind_kph": 1.1,
        "wind_degree": 340,
        "wind_dir": "NNW",
        "pressure_mb": 1004,
        "pressure_in": 29.64,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 81,
        "cloud": 71,
        "feelslike_c": 2.5,
        "feelslike_f": 36.5,
        "windchill_c": 2.5,
        "windchill_f": 36.5,
        "heatindex_c": 2.5,
        "heatindex_f": 36.5,
        "dewpoint_c": -0.4,
        "dewpoint_f": 31.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 1.1,
        "gust_kph": 1.8,
        "uv": 0
    },
    {
        "time_epoch": 1736276400,
        "time": "2025-01-07 19:00",
        "temp_c": 2.5,
        "temp_f": 36.4,
        "is_day": 0,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 1.8,
        "wind_kph": 2.9,
        "wind_degree": 28,
        "wind_dir": "NNE",
        "pressure_mb": 1004,
        "pressure_in": 29.65,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 81,
        "cloud": 59,
        "feelslike_c": 2.5,
        "feelslike_f": 36.4,
        "windchill_c": 2.5,
        "windchill_f": 36.4,
        "heatindex_c": 2.5,
        "heatindex_f": 36.4,
        "dewpoint_c": -0.4,
        "dewpoint_f": 31.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 2.9,
        "gust_kph": 4.6,
        "uv": 0
    },
    {
        "time_epoch": 1736280000,
        "time": "2025-01-07 20:00",
        "temp_c": 2.2,
        "temp_f": 36,
        "is_day": 0,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 2.9,
        "wind_kph": 4.7,
        "wind_degree": 30,
        "wind_dir": "NNE",
        "pressure_mb": 1004,
        "pressure_in": 29.66,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 83,
        "cloud": 45,
        "feelslike_c": 1.1,
        "feelslike_f": 33.9,
        "windchill_c": 1.1,
        "windchill_f": 33.9,
        "heatindex_c": 2.2,
        "heatindex_f": 36,
        "dewpoint_c": -0.4,
        "dewpoint_f": 31.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 4.8,
        "gust_kph": 7.7,
        "uv": 0
    },
    {
        "time_epoch": 1736283600,
        "time": "2025-01-07 21:00",
        "temp_c": 1.8,
        "temp_f": 35.2,
        "is_day": 0,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 3.4,
        "wind_kph": 5.4,
        "wind_degree": 42,
        "wind_dir": "NE",
        "pressure_mb": 1004,
        "pressure_in": 29.66,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 85,
        "cloud": 32,
        "feelslike_c": 0.2,
        "feelslike_f": 32.4,
        "windchill_c": 0.2,
        "windchill_f": 32.4,
        "heatindex_c": 1.8,
        "heatindex_f": 35.2,
        "dewpoint_c": -0.5,
        "dewpoint_f": 31.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 5.7,
        "gust_kph": 9.3,
        "uv": 0
    },
    {
        "time_epoch": 1736287200,
        "time": "2025-01-07 22:00",
        "temp_c": 1.4,
        "temp_f": 34.6,
        "is_day": 0,
        "condition": {
            "text": "Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
            "code": 1006
        },
        "wind_mph": 2.5,
        "wind_kph": 4,
        "wind_degree": 35,
        "wind_dir": "NE",
        "pressure_mb": 1005,
        "pressure_in": 29.67,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 86,
        "cloud": 64,
        "feelslike_c": 0.6,
        "feelslike_f": 33,
        "windchill_c": 0.6,
        "windchill_f": 33,
        "heatindex_c": 1.5,
        "heatindex_f": 34.6,
        "dewpoint_c": -0.6,
        "dewpoint_f": 30.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 4.3,
        "gust_kph": 6.9,
        "uv": 0
    },
    {
        "time_epoch": 1736290800,
        "time": "2025-01-07 23:00",
        "temp_c": 1.3,
        "temp_f": 34.3,
        "is_day": 0,
        "condition": {
            "text": "Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
            "code": 1006
        },
        "wind_mph": 3.6,
        "wind_kph": 5.8,
        "wind_degree": 13,
        "wind_dir": "NNE",
        "pressure_mb": 1005,
        "pressure_in": 29.69,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 87,
        "cloud": 82,
        "feelslike_c": -0.4,
        "feelslike_f": 31.2,
        "windchill_c": -0.4,
        "windchill_f": 31.2,
        "heatindex_c": 1.3,
        "heatindex_f": 34.3,
        "dewpoint_c": -0.6,
        "dewpoint_f": 30.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 6.2,
        "gust_kph": 9.9,
        "uv": 0
    }
]